### PR TITLE
Data binding over list attributes 

### PR DESCRIPTION
**Pull request by apanizo**
When doing data binding over a list attribute, return an empty list or null if the received JSON is an empty array or null accordingly.

[Review on Reviewable](https://reviewable.io/reviews/arcbees/gwtquery/356)

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/ArcBees/gwtquery/pull/356" target="_blank">ReviewNinja

**Comment by jDramaix** [comment]
LGTM

**Comment by jDramaix** [comment]
Thanks and sorry for the delay

**Comment by manolo** [comment]
@apanizo although the patch is ok and tests pass, there is something wrong in JS implementation since tests do not pass in production mode (compiled)

     mvn clean package -> passes
     mvn clean package -Dtest-prod  -> fails : 
    
     Failed tests: 
      test_return_null_when_list_is_not_specified(com.google.gwt.query.client.dbinding.DataBindingTestGwt):      expected: null, actual: <[]>

**Pull request merged**
